spring:
  application:
    name: aibron_first_task

  datasource:
    url: jdbc:postgresql://localhost:5432/aibron
    username: myuser
    password: secret

  flyway:
    clean-disabled: false
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    pl:
      dk: TRACE
    org:
      flywaydb: TRACE
      hibernate:
        orm:
          jdbc:
            bind: TRACE